Robots:
  - Robot:
      Name: RobotUR5
      ID: 12344
      Address: "opc.tcp://localhost:4840"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
         - SimpleMove
         - TestSkill
         - MoveToWithSpeed
         - SetEndEffectorSkill
         - PickSkill
         - PickAndPlaceSkill
  - Robot:
      Name: RobotABB
      ID: 1234
      Address: "192.168.8.24:3300"
      OPCUARoboticsFile: RobotABB.xml
      Skills:
         - MoveToWithSpeed
         - SetEndEffectorSkill
         - PickSkill
         - PickAndPlaceSkill
         - TestSkill
  - Robot:
      Name: KukaIiwa
      ID: 123448
      Address: "192.168.8.24:3200"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
         - MoveToWithSpeed
         - SetEndEffectorSkill
         - PickSkill
         - PickAndPlaceSkill
         - Drilling
         - TestSkill
