SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "info"
           OPCUA: "error"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/home/jbg/Desktop/SAMY/SAMYCore/configFiles/Skills.yaml" 
        RobotsFile: "/home/jbg/Desktop/SAMY/SAMYCore/configFiles/RobotsConfiguration.yaml"
        InformationSourcesFile: "/home/jbg/Desktop/SAMY/SAMYCore/configFiles/InformationSources.yaml"
        DataBaseFile: "/home/jbg/Desktop/SAMY/SAMYCore/configFiles/UseCase1.yaml"
