Robots:
  - Robot:
      Name: TestRobot
      ID: 12344
      Address: "opc.tcp://localhost:4840"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
         - InitCanonSkill
         - EndCanonSkill
         - MessageSkill
         - MoveToSkill
         - MoveScrewSkill
         - MoveThroughToSkill
         - DwellSkill
         - ActuateJointsSkill
         - ConfigureJointReportsSkill
  #       - ConfigureJointReportSkill
         - SetDefaultJointPositionsTolerancesSkill
         - GetStatusSkill
         - CloseToolChangerSkill
         - OpenToolChangerSkill
         - SetRobotParametersSkill
         - SetEndeffectorParametersSkill
         - SetEndeffectorSkill
         - SetTransAccelSkill
         - SetTransSpeedSkill
         - SetRotAccelSkill
         - SetRotSpeedSkill
         - SetAngleUnitsSkill
         - SetEndPoseToleranceSkill
         - SetForceUnitsSkill
         - SetIntermediatePoseToleranceSkill
         - SetLengthUnitsSkill
         - SetMotionCoordinationSkill
         - SetTorqueUnitsSkill
         - StopMotionSkill
         - ConfigureStatusReportSkill
         - EnableSensorSkill
         - DisableSensorSkill
         - EnableGripperSkill
         - DisableGripperSkill
         - EnableRobotParameterStatusSkill
         - DisableRobotParameterStatusSkill
