SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "info"
           OPCUA: "error"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/TestSkills.yaml"
        RobotsFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/TestRobotsConfiguration.yaml"
        InformationSourcesFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/TestInformationSources.yaml"
        DataBaseFile: "/home/jbg/Desktop/SAMY/SAMYCore/configFiles/UseCase1.yaml"
