Robots:
  - Robot:
      Name: RobotUR5
      ID: 1
      Address: "opc.tcp://localhost:4840"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
        - SimpleMove
        - MoveToWithSpeed
        - SetEndEffectorSkill
        - PickSkill
        - PickAndPlaceSkill
  - Robot:
      Name: Mir100
      ID: 2
      Address: "192.168.8.24:3300"
      OPCUARoboticsFile: RobotABB.xml
      Skills:
        - StartMissionSkill
  - Robot:
      Name: RobotABB
      ID: 3
      Address: "192.168.8.24:3200"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
        - SimpleMove
        - MoveToWithSpeed
        - SetEndEffectorSkill
        - PickSkill
        - PickAndPlaceSkill
  - Robot:
      Name: RobotPLC
      ID: 4
      Address: "192.168.8.24:3100"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
        - DisableComponent
        - EnableComponent
