SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "info"
           OPCUA: "debug"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/home/jbg/Desktop/SAMY/SAMYControl/UseCase1/configFiles/skills.yaml"
        RobotsFile: "/home/jbg/Desktop/SAMY/SAMYControl/UseCase1/configFiles/RobotsConfiguration.yaml"
        InformationSourcesFile: "/home/jbg/Desktop/SAMY/SAMYControl/UseCase1/configFiles/InformationSources.yaml"
        DataBaseFile: "/home/jbg/Desktop/SAMY/SAMYControl/UseCase1/configFiles/DataBaseFile.yaml"
