SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "error"
           OPCUA: "error"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/UseCaseFHTW"
        RobotsFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/UseCaseFHTW"
        InformationSourcesFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles/UseCaseFHTW"
        DataBaseFile: "/home/felix/Desktop/SAMY/Git/SAMYCore/configFiles"
